server:
  port: 8000

event_bus: kafka

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: accounting
      uri: mongodb://accounting:s3cr3t@mongo:27017/
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  rabbitmq:
    host: localhost
    port: 5672
    username: accounting
    password: s3cr3t
    virtual-host: accounting
    dynamic: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework: WARN
      flywaydb: WARN
      apache: WARN
      hibernate: WARN
    com:
      zaxxer: WARN
    nl:
      ivonet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

